[workspace]
members = [
    "web",
    "mdk/crates/mdk-core",
    "mdk/crates/mdk-sqlite-storage",
    "mdk/crates/mdk-storage-traits",
    "cdk/crates/cdk",
    "cdk/crates/cdk-sqlite",
    "cdk/crates/cashu",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
