services:
  nostr-relay:
    image: scsibug/nostr-rs-relay:latest
    container_name: nostr-relay
    ports:
      - "8080:8080"
    volumes:
      - ./nostr-relay-data:/usr/src/app/db
      - ./config.toml:/usr/src/app/config.toml
    environment:
      - RUST_LOG=info,nostr_rs_relay=info
    restart: unless-stopped
